"""created_at_column

Revision ID: 54089efb3922
Revises: 918a7bd18b7d
Create Date: 2023-04-29 14:54:02.023181

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54089efb3922'
down_revision = '918a7bd18b7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visualizers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True, server_update=sa.text('now()')))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visualizers', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
