"""empty message

Revision ID: 918a7bd18b7d
Revises: 5168c5ca593a
Create Date: 2023-04-27 09:37:39.713289

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '918a7bd18b7d'
down_revision = '5168c5ca593a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('_password_hash', sa.String(), nullable=True))
        batch_op.drop_column('password')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.drop_column('_password_hash')

    # ### end Alembic commands ###
